package com.objectfrontier.training.jdbc.exceptions;

public enum ErrorCode{

    F_NAME_NULL("First_Name is Null"),
    L_NAME_NULL("Last_Name is Null"),
    DOB_NULL("DOB is Null"),
    EMAIL_DUP("Email has been duplicated"),
    ID_NULL("Id Not exists"),
    LIST_EMPTY("List is empty"),
    ADDR_EMPTY("Address not found"),
    F_L_NAME_UNIQUE("First and Last name is unique"),
    VALIDATION_FAIL("Validation is fail"),
    STREET_NULL("Street is null"),
    CITY_NULL("City is null"),
    POSTAL_NULL("Postal Code is null"),
    DATE_FORMAT_ERROR("DateFormat is Mismatched"),
    ID_NOT_AUTOGENERATED("Id is not autogenerated"),
    SERVER("Internal Server error");

    private final String msg;

    ErrorCode(String msg) {
        this.msg = msg;
    }

    public String getMsg() {
        return this.msg;
    }
}
